
###
##nuevo OK

POST  http://localhost:8090/auth/nuevo HTTP/1.1
Content-Type: application/json

{
    "nickname": "pruebaProyeAdmin",
    "nombre":"prueba Proyecte",
    "email":"hectorproyeAdmin@gmail.com",
    "password":"NoTeLoDigo@1",
    "roles":["ROLE_ADMIN"]
}

###
##login OK

POST  http://localhost:8090/auth/login HTTP/1.1
Content-Type: application/json

{
    "nickname": "pruebaProyeAdmin",
    "password":"NoTeLoDigo@1"
    
}

##Muestra Animales
###
GET  http://localhost:8090/api/animal/animales HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcnVlYmFQcm95ZUFkbWluIiwiaWF0IjoxNzA3NzU0MjUwLCJleHAiOjE3MDc3OTAyNTB9.NVkX6Bq3TG0ucrhVA4LoNyLJK8ZjiHMeZ8vZ5O6YWSU

##Muestra Ganaderias por ID
###
GET  http://localhost:8090/api/ganaderia/ganaderia/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcnVlYmFQcm95ZUFkbWluIiwiaWF0IjoxNzA3NzU0MjUwLCJleHAiOjE3MDc3OTAyNTB9.NVkX6Bq3TG0ucrhVA4LoNyLJK8ZjiHMeZ8vZ5O6YWSU

##Muestra Animales por ID
###
GET http://localhost:8090/api/animal/animales/1002 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcnVlYmFQcm95ZUFkbWluIiwiaWF0IjoxNzA3NzU0MjUwLCJleHAiOjE3MDc3OTAyNTB9.NVkX6Bq3TG0ucrhVA4LoNyLJK8ZjiHMeZ8vZ5O6YWSU

##Crea Ganaderias
###
POST http://localhost:8090/api/ganaderia/crearganaderia HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcnVlYmFQcm95ZUFkbWluIiwiaWF0IjoxNzA3NzM1NTM3LCJleHAiOjE3MDc3NzE1Mzd9.Gepc__iyIePUbb8ysMj8N3G1El_vF1JYJTeLjk_ETWU
Content-Type: application/json

{
    "nombre_ganaderia": "Nombre de la Ganadería",
    "dueño": "Nombre del Dueño",
    "numero_animales": 100
}


##Crea Animales
###
POST http://localhost:8090/api/animal/crearanimal HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJwcnVlYmFQcm95ZUFkbWluIiwiaWF0IjoxNzA3NzM1NTM3LCJleHAiOjE3MDc3NzE1Mzd9.Gepc__iyIePUbb8ysMj8N3G1El_vF1JYJTeLjk_ETWU
Content-Type: application/json

{
    "crotal": 1789,
    "numero": 62,
    "nombre": "Pajarita",
    "edad": 3,
    "guarismo": 7
}

